spring:
  application:
    name: ${artifactId}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/mydatabase
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: secret
    hikari:
      connection-timeout: 5000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 10
      minimum-idle: 10
      pool-name: ConPool
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      connection.provider_class: com.zaxxer.hikari.hibernate.HikariConnectionProvider
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: ${port}
  servlet:
    context-path: ${contextPath}


